# include configuration variables
SRC_ROOT= ../src/
include $(SRC_ROOT)Makefile.incl

default:
	echo images here, nothing to build.

install:
	cp spectrast_tiny.png ${HTML_DIR}/images
	chmod 775 ${HTML_DIR}/images/spectrast_tiny.png	
	cp pa_tiny.png ${HTML_DIR}/images
	chmod 775 ${HTML_DIR}/images/pa_tiny.png	
	cp qMark.png ${HTML_DIR}/images
	chmod 775 ${HTML_DIR}/images/qMark.png	
