
# include configuration variables
SRC_ROOT= ../src/
include $(SRC_ROOT)Makefile.incl

all:
	echo image files, nothing to build.

install:
	cp pep-proph.jpg ${HELP_DIR}
	cp prot-proph.jpg ${HELP_DIR}
	cp protxml_help00.png ${HELP_DIR}
	cp protxml_help010.png ${HELP_DIR}
	cp protxml_help0115.png ${HELP_DIR}
	cp protxml_help01.png ${HELP_DIR}
	cp protxml_help02.png ${HELP_DIR}
	cp protxml_help03.png ${HELP_DIR}
	cp protxml_help04.png ${HELP_DIR}
	cp protxml_help05.png ${HELP_DIR}
	cp protxml_help06.png ${HELP_DIR}
	cp protxml_help07.png ${HELP_DIR}
	cp protxml_help085.png ${HELP_DIR}
	cp protxml_help086.png ${HELP_DIR}
	cp protxml_help087.png ${HELP_DIR}
	cp protxml_help08.png ${HELP_DIR}
	cp protxml_help.png ${HELP_DIR}
	cp pipeline_help10.png ${HELP_DIR}
	cp pipeline_help12.png ${HELP_DIR}
	cp pipeline_help1.png ${HELP_DIR}
	cp pipeline_help3.png ${HELP_DIR}
	cp pipeline_help5.png ${HELP_DIR}
	cp pipeline_help7.png ${HELP_DIR}
	cp pipeline_help9.png ${HELP_DIR}
	cp pipeline_help11.png ${HELP_DIR}
	cp pipeline_help13.png ${HELP_DIR}
	cp pipeline_help2.png ${HELP_DIR}
	cp pipeline_help4.png ${HELP_DIR}
	cp pipeline_help6.png ${HELP_DIR}
	cp pipeline_help8.png ${HELP_DIR}


